name: magnetic_form_builder_example
description: Example app demonstrating magnetic_form_builder package usage.
version: 1.0.0

environment:
  sdk: ^3.7.2
  flutter: ">=3.7.2"

dependencies:
  flutter:
    sdk: flutter
  magnetic_form_builder:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true